// <auto-generated />
namespace DBLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newproperties_08032018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newproperties_08032018));
        
        string IMigrationMetadata.Id
        {
            get { return "201803080853493_new-properties_08-03-2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
