// <auto-generated />
namespace DBLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RIC_Job_Report_Prop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RIC_Job_Report_Prop));
        
        string IMigrationMetadata.Id
        {
            get { return "201804180841450_RIC_Job_Report_Prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
