// <auto-generated />
namespace DBLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class propName_Cahenge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(propName_Cahenge));
        
        string IMigrationMetadata.Id
        {
            get { return "201803081058468_propName_Cahenge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
