// <auto-generated />
namespace DBLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Tbl_SubmissionRule : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tbl_SubmissionRule));
        
        string IMigrationMetadata.Id
        {
            get { return "201803091412386_Tbl_SubmissionRule"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
