// <auto-generated />
namespace DBLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class review_update_dirID_Hr_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(review_update_dirID_Hr_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201809171337370_review_update_dirID_Hr_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
