// <auto-generated />
namespace DBLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RefreshAnnualFeedbackTbls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RefreshAnnualFeedbackTbls));
        
        string IMigrationMetadata.Id
        {
            get { return "201810081359061_RefreshAnnualFeedbackTbls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
