// <auto-generated />
namespace DBLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class review_tabel31072018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(review_tabel31072018));
        
        string IMigrationMetadata.Id
        {
            get { return "201807310628337_review_tabel-31-07-2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
