// <auto-generated />
namespace DBLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_Prop_Notification_Type_30_10_2018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Prop_Notification_Type_30_10_2018));
        
        string IMigrationMetadata.Id
        {
            get { return "201810300720244_add_Prop_Notification_Type_30_10_2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
