namespace DBLibrary.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ApiAllsave : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_id", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_contact_id", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_company_id", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_company", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_reference", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_optional_reference", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_job_title", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_address1", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_address2", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_city", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_state", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_country", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_zipcode", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_first_name", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_last_name", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_department", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_job_status", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_job_type", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_issue_date", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_start_date", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_end_date", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_minimum_rate", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_maximum_rate", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_minimum_bill_rate", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_maximum_bill_rate", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_ID", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_DATEISSUED", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_DATEUPDATED", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_DATEUSERFIELDUPDATED", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_JOBSTATUS", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CUSTOMERID", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_COMPANYID", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_ADDRESS1", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_ADDRESS2", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CITY", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_STATE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_ZIPCODE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_PRIORITY", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_DIVISION", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_REFNO", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_JOBDIVANO", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_STARTDATE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_ENDDATE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_POSITIONS", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_FILLS", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_MAXALLOWEDSUBMITTALS", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_BILLRATEMIN", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_BILLRATEMAX", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_BILLRATEPER", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_AYRATEMIN", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_PAYRATEMAX", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_AYRATEPER", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_POSITIONTYPE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_SKILLS", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_JOBTITLE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_JOBDESCRIPTION", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_REMARKS", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_SUBMITTALINSTRUCTION", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_POSTTOPORTAL", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_POSTING_TITLE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_POSTING_DATE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_POSTINGDESCRIPTION", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CRITERIA_DEGREE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_JOBCATALOGID", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGCOMPANYID", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGTITLE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGREFNO", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGNAME", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGACTIVE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGEFFECTIVEDATE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGEXPIRATIONDATE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGCATEGORY", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGBILLRATELOW", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGBILLRATEHIGH", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGBILLRATEPER", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGPAYRATELOW", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGPAYRATEHIGH", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGPAYRATEPER", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_POSITIONREFNO", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_PREVENTLOWERPAY", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_PREVENTHIGHERBILL", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGNOTES", c => c.String());
            DropColumn("dbo.RMS_SharedReq_Dtl", "contact_id");
            DropColumn("dbo.RMS_SharedReq_Dtl", "company_id");
            DropColumn("dbo.RMS_SharedReq_Dtl", "company");
            DropColumn("dbo.RMS_SharedReq_Dtl", "optional_reference");
            DropColumn("dbo.RMS_SharedReq_Dtl", "address2");
            DropColumn("dbo.RMS_SharedReq_Dtl", "country");
            DropColumn("dbo.RMS_SharedReq_Dtl", "zipcode");
            DropColumn("dbo.RMS_SharedReq_Dtl", "first_name");
            DropColumn("dbo.RMS_SharedReq_Dtl", "last_name");
            DropColumn("dbo.RMS_SharedReq_Dtl", "department");
            DropColumn("dbo.RMS_SharedReq_Dtl", "job_type");
            DropColumn("dbo.RMS_SharedReq_Dtl", "start_date");
            DropColumn("dbo.RMS_SharedReq_Dtl", "end_date");
            DropColumn("dbo.RMS_SharedReq_Dtl", "minimum_rate");
            DropColumn("dbo.RMS_SharedReq_Dtl", "maximum_rate");
            DropColumn("dbo.RMS_SharedReq_Dtl", "minimum_bill_rate");
            DropColumn("dbo.RMS_SharedReq_Dtl", "maximum_bill_rate");
            DropColumn("dbo.RMS_SharedReq_Dtl", "DATEISSUED");
            DropColumn("dbo.RMS_SharedReq_Dtl", "DATEUPDATED");
            DropColumn("dbo.RMS_SharedReq_Dtl", "DATEUSERFIELDUPDATED");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CUSTOMERID");
            DropColumn("dbo.RMS_SharedReq_Dtl", "COMPANYID");
            DropColumn("dbo.RMS_SharedReq_Dtl", "REFNO");
            DropColumn("dbo.RMS_SharedReq_Dtl", "JOBDIVANO");
            DropColumn("dbo.RMS_SharedReq_Dtl", "STARTDATE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "ENDDATE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "POSITIONS");
            DropColumn("dbo.RMS_SharedReq_Dtl", "FILLS");
            DropColumn("dbo.RMS_SharedReq_Dtl", "MAXALLOWEDSUBMITTALS");
            DropColumn("dbo.RMS_SharedReq_Dtl", "BILLRATEMIN");
            DropColumn("dbo.RMS_SharedReq_Dtl", "BILLRATEPER");
            DropColumn("dbo.RMS_SharedReq_Dtl", "AYRATEMIN");
            DropColumn("dbo.RMS_SharedReq_Dtl", "AYRATEPER");
            DropColumn("dbo.RMS_SharedReq_Dtl", "POSITIONTYPE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SKILLS");
            DropColumn("dbo.RMS_SharedReq_Dtl", "JOBTITLE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "JOBDESCRIPTION");
            DropColumn("dbo.RMS_SharedReq_Dtl", "REMARKS");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SUBMITTALINSTRUCTION");
            DropColumn("dbo.RMS_SharedReq_Dtl", "POSTTOPORTAL");
            DropColumn("dbo.RMS_SharedReq_Dtl", "POSTING_TITLE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "POSTING_DATE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "POSTINGDESCRIPTION");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CRITERIA_DEGREE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "JOBCATALOGID");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CATALOGCOMPANYID");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CATALOGTITLE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CATALOGREFNO");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CATALOGNAME");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CATALOGACTIVE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CATALOGEFFECTIVEDATE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CATALOGEXPIRATIONDATE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CATALOGCATEGORY");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CATALOGBILLRATELOW");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CATALOGBILLRATEHIGH");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CATALOGBILLRATEPER");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CATALOGPAYRATELOW");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CATALOGPAYRATEHIGH");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CATALOGPAYRATEPER");
            DropColumn("dbo.RMS_SharedReq_Dtl", "POSITIONREFNO");
            DropColumn("dbo.RMS_SharedReq_Dtl", "PREVENTLOWERPAY");
            DropColumn("dbo.RMS_SharedReq_Dtl", "PREVENTHIGHERBILL");
            DropColumn("dbo.RMS_SharedReq_Dtl", "CATALOGNOTES");
        }
        
        public override void Down()
        {
            AddColumn("dbo.RMS_SharedReq_Dtl", "CATALOGNOTES", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "PREVENTHIGHERBILL", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "PREVENTLOWERPAY", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "POSITIONREFNO", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "CATALOGPAYRATEPER", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "CATALOGPAYRATEHIGH", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "CATALOGPAYRATELOW", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "CATALOGBILLRATEPER", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "CATALOGBILLRATEHIGH", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "CATALOGBILLRATELOW", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "CATALOGCATEGORY", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "CATALOGEXPIRATIONDATE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "CATALOGEFFECTIVEDATE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "CATALOGACTIVE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "CATALOGNAME", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "CATALOGREFNO", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "CATALOGTITLE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "CATALOGCOMPANYID", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "JOBCATALOGID", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "CRITERIA_DEGREE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "POSTINGDESCRIPTION", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "POSTING_DATE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "POSTING_TITLE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "POSTTOPORTAL", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SUBMITTALINSTRUCTION", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "REMARKS", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "JOBDESCRIPTION", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "JOBTITLE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "SKILLS", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "POSITIONTYPE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "AYRATEPER", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "AYRATEMIN", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "BILLRATEPER", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "BILLRATEMIN", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "MAXALLOWEDSUBMITTALS", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "FILLS", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "POSITIONS", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "ENDDATE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "STARTDATE", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "JOBDIVANO", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "REFNO", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "COMPANYID", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "CUSTOMERID", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "DATEUSERFIELDUPDATED", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "DATEUPDATED", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "DATEISSUED", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "maximum_bill_rate", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "minimum_bill_rate", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "maximum_rate", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "minimum_rate", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "end_date", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "start_date", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "job_type", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "department", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "last_name", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "first_name", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "zipcode", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "country", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "address2", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "optional_reference", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "company", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "company_id", c => c.String());
            AddColumn("dbo.RMS_SharedReq_Dtl", "contact_id", c => c.String());
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGNOTES");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_PREVENTHIGHERBILL");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_PREVENTLOWERPAY");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_POSITIONREFNO");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGPAYRATEPER");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGPAYRATEHIGH");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGPAYRATELOW");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGBILLRATEPER");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGBILLRATEHIGH");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGBILLRATELOW");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGCATEGORY");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGEXPIRATIONDATE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGEFFECTIVEDATE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGACTIVE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGNAME");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGREFNO");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGTITLE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CATALOGCOMPANYID");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_JOBCATALOGID");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CRITERIA_DEGREE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_POSTINGDESCRIPTION");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_POSTING_DATE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_POSTING_TITLE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_POSTTOPORTAL");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_SUBMITTALINSTRUCTION");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_REMARKS");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_JOBDESCRIPTION");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_JOBTITLE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_SKILLS");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_POSITIONTYPE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_AYRATEPER");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_PAYRATEMAX");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_AYRATEMIN");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_BILLRATEPER");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_BILLRATEMAX");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_BILLRATEMIN");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_MAXALLOWEDSUBMITTALS");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_FILLS");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_POSITIONS");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_ENDDATE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_STARTDATE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_JOBDIVANO");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_REFNO");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_DIVISION");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_PRIORITY");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_ZIPCODE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_STATE");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CITY");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_ADDRESS2");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_ADDRESS1");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_COMPANYID");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_CUSTOMERID");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_JOBSTATUS");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_DATEUSERFIELDUPDATED");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_DATEUPDATED");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_DATEISSUED");
            DropColumn("dbo.RMS_SharedReq_Dtl", "GetBIDataApi_JobDetails_ID");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_maximum_bill_rate");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_minimum_bill_rate");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_maximum_rate");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_minimum_rate");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_end_date");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_start_date");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_issue_date");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_job_type");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_job_status");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_department");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_last_name");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_first_name");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_zipcode");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_country");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_state");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_city");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_address2");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_address1");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_job_title");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_optional_reference");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_reference");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_company");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_company_id");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_contact_id");
            DropColumn("dbo.RMS_SharedReq_Dtl", "SearchJobApi_id");
        }
    }
}
