// <auto-generated />
namespace DBLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ric_review_1__17_09_2018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ric_review_1__17_09_2018));
        
        string IMigrationMetadata.Id
        {
            get { return "201809170858409_ric_review_1__17_09_2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
