// <auto-generated />
namespace DBLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TargetTable_fixUpdateddate090519 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TargetTable_fixUpdateddate090519));
        
        string IMigrationMetadata.Id
        {
            get { return "201905091212015_TargetTable_fixUpdateddate090519"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
