// <auto-generated />
namespace DBLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RIC_UserDashboardPanel_ColumnWidth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RIC_UserDashboardPanel_ColumnWidth));
        
        string IMigrationMetadata.Id
        {
            get { return "201906130827485_RIC_UserDashboardPanel_ColumnWidth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
