// <auto-generated />
namespace DBLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class JobChecked_InOut_Info : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JobChecked_InOut_Info));
        
        string IMigrationMetadata.Id
        {
            get { return "202004170802300_JobChecked_InOut_Info"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
